version: "3.3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=birra-meet
      - MONGO_INITDB_ROOT_PASSWORD=birra
      - MONGO_INITDB_DATABASE=birra-meet
  redis:
    image: redis
    ports:
      - 6379:6379